eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/
            fetchRegistry: true
server:
    port: 8001

spring:
    application:
        name: UserService
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
            path: /console
            settings:
                web-allow-others: true
